### ISSUE TITLE
Does ScopeLocals support as context for single thread processing?

### ISSUE THREAD

**Issue by mingjliu9** [theRealAph/ScopeLocals#1]
Say a thread could fulfill all the required actions for a kind of HTTP Request, then, If there need to add some "hidden" context through library codes (SLF4J MDC as an example). In this scenario, does ScopeLocals fit in?

The reason for this questions is regarding to keep the stacktrace. A full Stracktrace is helpful and is intuitive to problem analysis, and I think it is what Loom project is valuing (the syncing way do async I/O job, not sure still being now).

Thanks!

**Comment by theRealAph** [comment]
Loom solves a ton of problems with async programming, effectively by doing sync programming with virtual threads and making async programming go away. Therefore you'll get nice stack traces.

I'll quite Brian Goetz here:

  - ThreadLocal (and inheritable ThreadLocal especially) were always compromises, and with  the advent of Loom, have become untenable -- but the need for implicit  parameters has not gone away
  - Scoped locals, because of their effective finality and dynamic scoping, offer a programming model that is a better fit for virtual 
threads, but, even in the absence of virtual threads, are an enabler for structured concurrency
  - The programming model constraints enable a better-performing implementation

**Comment by mingjliu9** [comment]
Thanks for your comments!

My understanding is that, as structured concurrency would maintain the the lightweight thread hierarchy, it would be able to trace back to the origin lightweight thread (thread) which initialized the calls.
